# This is a basic workflow to help you get started with Actions


name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Trivy
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
        
      # - name: Run Trivy vulnerability scanner
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     args: trivy image --format sarif -o results.sarif ubuntu

      - name: Run Trivy vulnerability scanner
        run: trivy image --format sarif -o results.sarif httpd
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: results.sarif
         
      # - name: Run Trivy vulnerability scanner in fs mode
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     image-ref: 'docker.io/hub.docker.com/_/httpd'
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4.1.0
      #   if: always()
      #   with:
      #     name: trivy-ref
      #     sarif_path: 'trivy-results.sarif'
    
                
