# This is a basic workflow to help you get started with Actions


name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: OS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in fs mode
        uses: Ishita82/trivy-GitAction@main
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          sarif_path: 'image-sarif.test'
    
                
