# This is a basic workflow to help you get started with Actions


name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: OS
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Trivy vulnerability scanner
        uses: Ishita82/trivy-GitAction@main
        with:
         image-ref: httpd
         format: 'sarif'
         output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
         sarif_file: 'trivy-results.sarif' 
      # - name: Run Trivy vulnerability scanner in fs mode
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     image-ref: 'docker.io/hub.docker.com/_/httpd'
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4.1.0
      #   if: always()
      #   with:
      #     name: trivy-ref
      #     sarif_path: 'trivy-results.sarif'
    
                
