name: Trivy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Trivy Scanning
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      # packages: write
      # id-token: write
      security-events: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      
      - name: Run Trivy vulnerability scanner
        run: trivy image --format sarif -o results.sarif httpd
        
      # - name: Run Trivy vulnerability scanner
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     args: trivy image --format sarif -o results.sarif ubuntu

      # - name: Run Trivy vulnerability scanner
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     scan-type: 'config'
      #     hide-progress: false
      #     format: 'sarif'
      #     output: 'results.sarif'
      #     exit-code: '1'
      #     ignore-unfixed: true
      # - name: Check Trivy Scan Results
      #   run: cat results.sarif
        
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: 'results.sarif'

      - name: Check Trivy Scan Results
        run: |
          # Print the structure of the SARIF file
          # jq . results.sarif
      
          CRITICAL_COUNT=$(jq -r '.runs[].tool.driver.rules | select(.!=null) | map(select(.properties.severity == "LOW")) | length' results.sarif)
          echo $CRITICAL_COUNT
          
          if [ $CRITICAL_COUNT -gt 0 ]; then
            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
            exit 1
          else
            echo "Trivy scan passed without critical vulnerabilities."
          fi



