# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write
  repository-projects: write
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRIVY_ACCESS }}  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'results.sarif'
          severity: 'LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'results.sarif'
          token: ${{ secrets.TRIVY_ACCESS }}
