name: Trivy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Trivy Scanning
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      # packages: write
      # id-token: write
      security-events: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install trivy
      #   run: |
      #     sudo apt-get install wget apt-transport-https gnupg lsb-release
      #     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      #     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
      #     sudo apt-get update
      #     sudo apt-get install trivy
      
      # - name: Run Trivy vulnerability scanner
      #   run: trivy image --format sarif -o results.sarif httpd
        
      # - name: Run Trivy vulnerability scanner
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     args: trivy image --format sarif -o results.sarif ubuntu

      # - name: Run Trivy vulnerability scanner
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     scan-type: 'git'
      #     hide-progress: false
      #     format: 'sarif'
      #     output: 'results.sarif'
      #     exit-code: '1'
      #     ignore-unfixed: true

      # - name: Trivy Image Scan
      #   uses: Ishita82/trivy-GitAction@main
      #   with:
      #     image-ref: nginx:latest
      #     format: json
      #     output: results.json

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'results.sarif'
          severity: 'LOW'

      # - name: Check Trivy Scan Results
      #   run: cat results.sarif
        
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          name: Scanning Results
          sarif_file: results.sarif
      
      - name: Count LOW occurrences
        id: count_low
        run: |
          CRITICAL_COUNT=$(cat results.sarif | grep -c CRITICAL || true)
          echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> $GITHUB_ENV

      - name: Display CRITICAL_COUNT
        run: |
          echo "CRITICAL_COUNT is $CRITICAL_COUNT"

      - name: Check for Critical Vulnerabilities
        run: |
          if [ $CRITICAL_COUNT -gt 0 ]; then
            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
            exit 1
          else
            echo "Trivy scan passed without critical vulnerabilities."
          fi



